### ISSUE TITLE
Configuration problems, unable to output anything

### ISSUE THREAD

**Issue by ThePeach** [AlansCodeLog/metalsmith-organizer#1]
First of all, many thanks for this plugin, as at first it does seem like it tries to solve a common problem of configuring too many plugins just to set up a blog.

So I've been using metalsmith-permalinks, metalsmith-collections, metalsmith-tags and was trying to get some sort of pagination working without much success, hence the reason why I landed on this plugin.

Consider that I'm moving from my old drupal-generated blog, so I have very little space for manoeuvre changing permalinks due to the limited possibility of redirection on static hosting.

I have only `articles` (posts, with a permalink similar to `/YYYY/MM/DD/title/`) and `pages` (contact, and few others if needed, with a simple permalink like `/title/`).

These two are currently folder-organised, rather than using a property, as I'd like to write as little meta information as needed. 

As far as I've understood the grouping of the _"types"_ happens only via YAML properties, although it's not clear from the documentation what this property needs to be: e.g. with metalsmith-collections it used to be `collection`, so I wonder if I can use anything of the likes.

For my specific instance, it would be great to be able to group posts using a glob pattern, e.g. `articles/**/*.md` but I wonder if it's too much to ask.

The second aspect I wanted to understand in regards to the configuration, is whether it's possible to achieve something like the following for the index and archive pages:

the idea is the following:
in the homepage, I will iterate through the first _"page"_ of articles and provide a link to _"older"_ posts, i.e. the *archive*.

The archive is going to work in pages: `/archive/page/1/` etc. and contain all older articles starting from where the homepage left off.

I hope that makes sense so far and thanks for taking the time to go through all of the above!

**Comment by alanscodelog** [comment]
Again as I mentioned in your pull request comment so sorry for the late reply, my notification settings were wrong and I wasn't notified of the issue. I hope I'm not too late to help.

Regarding the metadata "property" name there is none, as explained in Group Options > Search Criteria: any post property that is not a property already in use by the plugin can be used to "search" for posts. I used type as an example because that's what I used. But you could easily use a property called `collection`. And you would do something like:

```javascript
{
   group_name: "posts",
   collection: "post",
},
```

I will either update the documentation to clarify this or it's been a while since I wrote this, I'm considering splitting the search criteria into a group so what's happening is clearer:

```javascript
{
   group_name: "posts",
   //addon properties
   search_criteria: {
       collection: "post",
       draft: false,
       //etc
       //post properties
   }
},
```

This would also get simplify the code and allow for any property name.

As for the glob pattern this is something I specifically wanted to avoid. They are inflexible imo. My idea was to rely on metadata only. That way I can move around my markdown files (between folders like drafts, old, etc) and it doesn't affect the plugin. I will consider it though. Maybe it could be a property called `include_only` or `search_only_in`? So it would match against a glob and the search criteria.

As for how to do the archive you need. It's not really possible to split a group of posts (e.g. first ten do x, else do y). 

I have to check, but I think it should be possible to implement something like a `first_page_path` property though. So if the `per_page` is set to 10, the first ten posts will use one path and the rest another. Does that sound like what you were looking for?

**Comment by alanscodelog** [comment]
I am closing this issue because I'm no longer going to maintain this plugin since I am working on creating my own static site generator (with many of the options of this plugin, others I've made, and more).
